name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4.7.1
      with:
       distribution: 'adopt'
       java-version: '17'

# ./gradlew --no-daemon assembleRelease
    - name: Build the project
      run: |
        chmod +x ./gradlew && \
        ./gradlew -q :tasks --all && \
        ./gradlew composeApp:build 

# .\build\bin\native\
    - run: |
        ls -R
