name: CI
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
permissions:
    contents: write
    
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java JDK
      uses: actions/setup-java@v4.7.1
      with:
       distribution: 'adopt'
       java-version: '17'
       

    - name: Set up cocoapods
      uses: maxim-lobanov/setup-cocoapods@v1.4.0
      with:
        version: latest
        
# ./gradlew --no-daemon assembleRelease
    - name: Build the project
      run: |
        chmod +x ./gradlew && \
        ./gradlew -q :tasks --all && \
        ./gradlew build
      
        # ./gradlew shared:build && \
        # ./gradlew composeApp:build && \
        # compileKotlinIosX64


    # - shell: bash
    #   name: Install Dependencies
    #   run: |
    #     cd iosApp
    #     pod install --verbose
        
    # - run: |
    #     xcodebuild build -workspace iosApp/iosApp.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 14' -verbose

# .\build\bin\native\
    - run: |
        ls -R

    # - name: Archive Release
    #   uses: thedoctor0/zip-release@master
    #   with:
    #     type: 'zip'
    #     path: ${{ github.event.repository.name }}*
    #     filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
        
    - name: Release prebuilt
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          "composeApp/build/outputs/apk/debug/composeApp-debug.apk"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
